name: 'Terraform plan'
on:
  push:
    branches: 
      - main 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  terraform_plan:
    name: 'Terraform plan'
    runs-on: windows-latest
    #environment: production

    env: 
      ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secretS.SUBSCRIPTIONID }}
      ARM_TENANT_ID: ${{ secrets.TENANTID }}
            

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: login via Az module
      uses: azure/login@v1.4.0
      with: 
        creds: ${{ secrets.AZURE_RDAC }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.4

    - name: Terraform Init azurem backend
      run: | 
        terraform init -input=false \
         -backend-config="resource_group_name=demorg" \
         -backend-config="storage_account_name=appstoreinfun" \
         -backend-config="container_name=gacttfstore" \
         -backend-config="key=terraformrg.tfstate" \
         -backend-config=client_secret="DV88Q~cYesBNZR~YSL0k4LLxY6i2SAokjluf~dbn" \
         -backend-config=client_id="6b35eae6-1065-4a6f-b59e-356d9dd42d2e" \
         -backend-config=tenant_id="90b59039-d7b6-4056-bd4a-0c8614d852a8" \
         -backend-config=subscription_id="8cd9cb10-8a19-44a1-a5b7-3290ef2b3a24"
       

       # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -out=plan.tfplan -input=false -var-file="env/dev.tfvars"

 
